export const facilities = [
    {
        id: 1,
        name: 'City General Hospital',
        type: 'Hospital',
        address: '123 Main Street, Downtown',
        phone: '(555) 123-4567',
        rating: 4.5,
        specialties: ['Emergency', 'Surgery', 'Cardiology'],
        distance: '2.3 km',
        description: 'A leading healthcare facility providing comprehensive medical services with state-of-the-art equipment and experienced medical professionals.',
        hours: 'Monday - Friday: 8:00 AM - 8:00 PM\nSaturday: 9:00 AM - 5:00 PM\nSunday: Closed',
        reviews: 245,
    },
    {
        id: 2,
        name: 'Green Valley Clinic',
        type: 'Clinic',
        address: '456 Oak Avenue, Westside',
        phone: '(555) 234-5678',
        rating: 4.8,
        specialties: ['General Practice', 'Pediatrics'],
        distance: '1.5 km',
        description: 'Family-friendly clinic specializing in general practice and pediatric care with a warm, welcoming environment.',
        hours: 'Monday - Friday: 9:00 AM - 6:00 PM\nSaturday: 10:00 AM - 2:00 PM\nSunday: Closed',
        reviews: 187,
    },
    {
        id: 3,
        name: 'Advanced Dental Care',
        type: 'Dental',
        address: '789 Elm Street, Eastside',
        phone: '(555) 345-6789',
        rating: 4.6,
        specialties: ['Dentistry', 'Orthodontics'],
        distance: '3.1 km',
        description: 'Modern dental practice offering comprehensive dental care and orthodontic services with the latest technology.',
        hours: 'Monday - Friday: 8:00 AM - 7:00 PM\nSaturday: 9:00 AM - 3:00 PM\nSunday: Closed',
        reviews: 156,
    },
    {
        id: 4,
        name: 'Wellness Medical Center',
        type: 'Medical Center',
        address: '321 Pine Road, Northside',
        phone: '(555) 456-7890',
        rating: 4.7,
        specialties: ['Internal Medicine', 'Dermatology'],
        distance: '4.2 km',
        description: 'Comprehensive medical center focusing on preventive care and specialized treatments for various conditions.',
        hours: 'Monday - Friday: 7:00 AM - 8:00 PM\nSaturday: 8:00 AM - 4:00 PM\nSunday: Closed',
        reviews: 203,
    },
    {
        id: 5,
        name: 'Riverside Urgent Care',
        type: 'Urgent Care',
        address: '654 River Drive, Southside',
        phone: '(555) 567-8901',
        rating: 4.4,
        specialties: ['Urgent Care', 'X-Ray'],
        distance: '2.8 km',
        description: 'Walk-in urgent care facility providing immediate medical attention for non-life-threatening conditions.',
        hours: 'Monday - Sunday: 8:00 AM - 10:00 PM',
        reviews: 312,
    },
    {
        id: 6,
        name: 'Family Health Clinic',
        type: 'Clinic',
        address: '987 Maple Lane, Central',
        phone: '(555) 678-9012',
        rating: 4.9,
        specialties: ['Family Medicine', 'Vaccinations'],
        distance: '1.2 km',
        description: 'Trusted family clinic providing personalized healthcare services for patients of all ages.',
        hours: 'Monday - Friday: 8:00 AM - 6:00 PM\nSaturday: 9:00 AM - 1:00 PM\nSunday: Closed',
        reviews: 428,
    },
];